sudo: required
language: scala
jdk:
    - openjdk8
install:
    - wget http://download.redis.io/releases/redis-5.0.1.tar.gz
    - tar -xzvf redis-5.0.1.tar.gz
    - make -C redis-5.0.1 -j4
    - export PATH=$PWD/redis-5.0.1/src:$PATH
script:
    - make test MVN_EXTRA_OPTS="-P scala-2.12"
    - ps aux | grep redis
    - make stop
    - ps aux | grep redis
    - make test
    - ps aux | grep redis
cache:
    directories:
        - $HOME/.m2
